version: '3.8'

services:
  app:
    build: .
    image: sspai-api:latest
    container_name: sspai-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    environment:
      # 在阿里云环境中，需要根据实际数据库地址修改
      - DATABASE_URL = "mysql+pymysql://root:Tian_1901@127.0.0.1:3306/abcd?charset=utf8mb4"
      - ENV=production
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  app_data:
    name: sspai-app-data
  app_logs:
    name: sspai-app-logs